### ISSUE TITLE
test投稿

### ISSUE THREAD

**Issue by isupport-kitta** [city-soja-chiiki/QGIS#1]
test

**Comment by city-soja-chiiki** [comment]
https://github.com/city-soja-chiiki/douro_daityou_hosei
の方を使ってください。
登録されて人しか見えない仕様になっています。
こちらはパブリック設定なので、公開になっています。
以上。

**Comment by isupport-kitta** [comment]
> https://github.com/city-soja-chiiki/douro_daityou_hosei の方を使ってください。 登録されて人しか見えない仕様になっ ています 。
申し訳ありません。招待の期限が切れているようです。
今一度送って下さい。よろしくお願いします。
